apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: suma-proxy-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - calculadora-suma
  selector:
    matchLabels:
      app: suma-proxy
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
