apiVersion: v1
kind: Service
metadata:
  name: suma-proxy
  namespace: calculadora-suma
spec:
  type: LoadBalancer
  selector:
    app: suma-proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
