{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "suma-basica.namespace" . }}
  labels:
{{ include "suma-basica.labels" . | indent 4 }}
{{- with .Values.commonLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
