{{- range $digit := .Values.digits }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suma-digito-{{ $digit.id }}
  namespace: {{ $.Values.namespace.name }}
  labels:
{{ include "suma-basica.labels" $ | indent 4 }}
    digito: {{ $digit.id | quote }}
{{- with $.Values.commonLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: {{ $digit.replicas }}
  selector:
    matchLabels:
      app: suma-backend
      digito: {{ $digit.id | quote }}
  template:
    metadata:
      labels:
        app: suma-backend
        digito: {{ $digit.id | quote }}
    spec:
{{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
{{- range $secret := $.Values.imagePullSecrets }}
        - name: {{ $secret }}
{{- end }}
{{- end }}
      containers:
        - name: suma-api
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: {{ $digit.service.targetPort }}
              name: http
          resources:
{{ toYaml $.Values.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: suma-digito-{{ $digit.id }}
  namespace: {{ $.Values.namespace.name }}
  labels:
{{ include "suma-basica.labels" $ | indent 4 }}
    digito: {{ $digit.id | quote }}
{{- with $.Values.commonLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ $digit.service.type }}
  selector:
    app: suma-backend
    digito: {{ $digit.id | quote }}
  ports:
    - port: {{ $digit.service.port }}
      targetPort: {{ $digit.service.targetPort }}
      protocol: TCP
      name: http
{{- if eq $digit.service.type "NodePort" }}
      nodePort: {{ $digit.service.nodePort }}
{{- end }}
{{- end }}
